spring:
  profiles:
    default: local

  # devtools
  devtools:
    livereload.enable: true
    restart.enable: true
  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        # backtic
        auto_quote_keyword: true

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.216.236:57287/LOLCI?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: diehreo
    password: 021548
    
  # thymeleaf
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html

logging:
  level:
    org:
      springframework:
        web: INFO
