spring:
  profiles:
    default: local
  devtools:
    livereload:
      enabled: true


  # JPA
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        # backtic
        auto_quote_keyword: true

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.216.236:57287/LOLCI?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: diehreo
    password: 021548
